name: check

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: setup-zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0

      - name: lint
        run: |
          zig fmt --check src/ build.zig

  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    timeout-minutes: 60
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: setup-zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0

      - name: test
        run: |
          zig build test
